version: '3'
services:
  springbootrestdemo:
    image: nico-test:latest
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:sqlserver://sql:1433;databaseName=starwars2'
      SPRING_DATASOURCE_USERNAME: 'sa'
      SPRING_DATASOURCE_PASSWORD: 'Geheim10'
      SPRING_JPA_HIBERNATE_DDL-AUTO: 'create'
      NICO_DATABASE_CREATE_URL: 'jdbc:sqlserver://sql:1433'
      NICO_DATABASE_CREATE_NAME: 'starwars2'
  sql:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Geheim10'
